CREATE TABLE IF NOT EXISTS Actors (
Name VARCHAR(40),
Movie VARCHAR(40),
Year INT,
Role VARCHAR(40));

LOAD DATA LOCAL INFILE '~/ebay-data/actors.csv' INTO TABLE Actors
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

SELECT Name FROM Actors
WHERE Movie='Die Another Day';

DROP TABLE IF EXISTS Actors;
