LOAD DATA LOCAL INFILE 'Item.dat' INTO TABLE Item FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '`' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Bid.dat' INTO TABLE Bid FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '`' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'User.dat' INTO TABLE User FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '`' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Category.dat' INTO TABLE Category FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '`' LINES TERMINATED BY '\n';
