LOAD DATA LOCAL INFILE 'Item.dat' INTO TABLE Item FIELDS OPTIONALLY ENCLOSED BY '`' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Bid.dat' INTO TABLE Bid FIELDS OPTIONALLY ENCLOSED BY '`' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'User.dat' INTO TABLE User FIELDS OPTIONALLY ENCLOSED BY '`' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Category.dat' INTO TABLE Category FIELDS OPTIONALLY ENCLOSED BY '`' LINES TERMINATED BY '\n';
